### ISSUE TITLE
Not visible after drag and dropping

### ISSUE THREAD

**Issue by Midhun-edv** [magento-devdocs/pagebuilder-examples#49]
i installed and tried your Quote module but when i drag and drop all its elements are coming but the its hidden i cant edit or do anything kindly solve this issue.it will be helpful
settings also not accessible
![Screenshot from 2024-09-26 18-24-12](https://github.com/user-attachments/assets/4c88950b-4372-41af-97ca-227f4e1f2423)

console error:
edit.js:106 Uncaught TypeError: Cannot read properties of undefined (reading 'breakpoints')
    at Edit.getFormNamespace (edit.js:106:36)
    at Edit.open (edit.js:78:25)
    at Preview.openEdit (preview.js:125:24)
    at Preview.onOptionEdit (preview.js:283:12)
    at Option.action (option.js:56:18)
    at Option.eval (eval at createBindingsStringEvaluator (knockout.js:3221:28), <anonymous>:3:157)
    at HTMLAnchorElement.<anonymous> (knockout.js:4669:74)
    at HTMLAnchorElement.dispatch (jquery.js:5430:49)
    at elemData.handle (jquery.js:5234:47)

**Comment by DraconaDS** [comment]
any updates regarding this problem? Same issue on my side with magento 2.4.7-p4

**Comment by Drako2711** [comment]
Same here

**Comment by thewebverse** [comment]
To solve this issue, in this .html file:
[Module]/view/adminhtml/web/template/content-type/custom-quote/default/preview.html

Change  `<render args="getOptions().template"/>` to: `<render args="getOptions().template"></render>`

Do this for all the Knockout virtual elements in this file. Other elements that need to be updated are in line 5 and 12;

`<render />` to: `<render></render>`
`<render args="template"/> `to: `<render args="template"></render>`

Hope this helps!
